Repository tamago3keran/shuffle_lunch, pull requests merged in 2020-01, with the labels that each got.

#38 fixed #26 AdminUserモデルの実装
  app/models/admin_user.rb
Labels: enhancement

#41 fixed #27 既存機能のAdmin移行
  app/controllers/admin/group_sets/applied_statuses_controller.rb
  app/controllers/admin/group_sets/groups_controller.rb
  app/controllers/admin/group_sets_controller.rb
  app/controllers/admin/users/activations_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/group_sets_controller.rb
  app/controllers/users/activations_controller.rb
  app/views/admin/group_sets/groups/edit.html.haml
  app/views/admin/group_sets/groups/new.html.haml
  app/views/admin/group_sets/index.html.haml
  app/views/admin/group_sets/new.html.haml
  app/views/admin/group_sets/show.html.haml
  app/views/admin/users/index.html.haml
  app/views/admin/users/new.html.haml
  app/views/group_sets/index.html.haml
  app/views/group_sets/show.html.haml
  app/views/users/index.html.haml
  config/routes.rb
Labels: enhancement

#39 fixed #30 レストランモデルの作成
  app/models/group.rb
  app/models/restaurant.rb
  app/models/restaurant_note.rb
Labels: enhancement

#42 fixed#31 お店一覧ページの作成
  app/assets/stylesheets/application.css
  app/assets/stylesheets/restaurant.css
  app/controllers/restaurants_controller.rb
  app/helpers/restaurants_helper.rb
  app/models/restaurant.rb
  app/views/restaurants/index.html.haml
  config/routes.rb
Labels: enhancement

#43 fixed #34 お店新規登録ページの実装
  app/assets/stylesheets/restaurant.css
  app/controllers/restaurants_controller.rb
  app/views/restaurants/index.html.haml
  app/views/restaurants/new.html.haml
  config/routes.rb
Labels: enhancement

#44 fixed #25 Adminログイン機能の実装
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/views/admin/group_sets/index.html.haml
  app/views/group_sets/show.html.haml
  app/views/sessions/new.html.haml
  config/routes.rb
  frontend/src/javascripts/pages/sessions/login_new.js
Labels: enhancement

#46 fixed #32 お店詳細ページの実装（レストランモデルに関する情報のみ対応）
  app/assets/stylesheets/restaurant.css
  app/controllers/restaurants_controller.rb
  app/models/restaurant_note.rb
  app/views/restaurants/index.html.haml
  app/views/restaurants/show.html.haml
Labels: enhancement

#54 fixed #37 お店削除機能の実装
  app/controllers/restaurants_controller.rb
Labels: enhancement

#57 fixed #48 flashメッセージの表示
  app/assets/stylesheets/application.css
  app/views/layouts/application.html.erb
Labels: enhancement

#59 fixed #35 Admin認可機能の実装
  app/assets/stylesheets/application.css
  app/assets/stylesheets/restaurant.css
  app/assets/stylesheets/session.css
  app/controllers/admin/group_sets/applied_statuses_controller.rb
  app/controllers/admin/group_sets/groups_controller.rb
  app/controllers/admin/group_sets_controller.rb
  app/controllers/admin/users/activations_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/models/group.rb
  app/views/group_sets/show.html.haml
  app/views/sessions/new.html.haml
Labels: enhancement

#60 fixed #23 グループ分け一覧ページの実装
  app/assets/stylesheets/group_sets.css
  app/views/group_sets/index.html.haml
Labels: enhancement

#56 fixed #45 お店口コミの表示・登録機能の作成
  app/assets/stylesheets/restaurant.css
  app/controllers/restaurant_notes_controller.rb
  app/controllers/restaurants_controller.rb
  app/models/restaurant.rb
  app/models/restaurant_note.rb
  app/views/restaurants/show.html.haml
  config/routes.rb
Labels: enhancement

#55 fixed #28 グループ詳細ページの実装
  app/assets/stylesheets/group_sets.css
  app/assets/stylesheets/session.css
  app/controllers/group_sets/groups_controller.rb
  app/views/group_sets/groups/edit.html.haml
  app/views/group_sets/groups/show.html.haml
  app/views/group_sets/show.html.haml
  app/views/sessions/new.html.haml
Labels: enhancement

#65 fixed #63 お店一覧ページに登録日を表示
  app/assets/stylesheets/restaurant.css
  app/views/restaurants/index.html.haml
Labels: enhancement

#62 fixed #29 グループ編集ページの実装
  app/assets/stylesheets/group_sets.css
  app/controllers/application_controller.rb
  app/controllers/group_sets/groups_controller.rb
  app/controllers/restaurants_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/views/group_sets/groups/edit.html.haml
  app/views/group_sets/groups/show.html.haml
  app/views/restaurants/new.html.haml
Labels: enhancement

#68 fixed #67 モーダルの文言修正
  app/views/restaurants/show.html.haml
Labels: enhancement

#69 fixed #64 フロントエンドの調整
  app/assets/stylesheets/application.css
  app/assets/stylesheets/common.css
  app/assets/stylesheets/default.css
  app/assets/stylesheets/group_sets.css
  app/assets/stylesheets/restaurant.css
  app/controllers/restaurants_controller.rb
  app/controllers/sessions_controller.rb
  app/views/admin/group_sets/groups/edit.html.haml
  app/views/admin/group_sets/groups/new.html.haml
  app/views/admin/group_sets/index.html.haml
  app/views/admin/group_sets/new.html.haml
  app/views/admin/group_sets/show.html.haml
  app/views/admin/users/index.html.haml
  app/views/admin/users/new.html.haml
  app/views/group_sets/groups/edit.html.haml
  app/views/group_sets/groups/show.html.haml
  app/views/group_sets/index.html.haml
  app/views/group_sets/show.html.haml
  app/views/restaurants/_form.html.haml
  app/views/restaurants/edit.html.haml
  app/views/restaurants/index.html.haml
  app/views/restaurants/new.html.haml
  app/views/restaurants/show.html.haml
  frontend/src/javascripts/components/Sidebar.js
Labels: enhancement

#73 fixed #71 Admin機能改善
  app/assets/stylesheets/common.css
  app/controllers/sessions_controller.rb
  app/models/admin_user.rb
  app/views/admin/group_sets/index.html.haml
  app/views/group_sets/index.html.haml
  app/views/layouts/application.html.erb
  frontend/src/javascripts/components/Sidebar.js
Labels: enhancement

#80 fixed #76 admin_userモデルのテスト実装
  spec/models/admin_user_spec.rb
Labels: test

#86 fixed #85 お店新規登録後のリダイレクト動作不具合
  app/controllers/group_sets/groups_controller.rb
  app/controllers/restaurants_controller.rb
  app/views/restaurants/new.html.haml
Labels: bug

#91 fixed #81 groupモデルのテスト実装
  spec/models/group_spec.rb
Labels: test

#97 fixed #96 usersコントローラのテスト実装
  spec/requests/restaurants_controller_spec.rb
  spec/requests/users_controller_spec.rb
Labels: test

#75 fixed #74 restaurantモデルのテスト実装
  app/models/restaurant.rb
  spec/models/restaurant_spec.rb
Labels: test

#78 fixed #77 restaurant_noteモデルのテスト実装
  app/models/restaurant_note.rb
  app/views/restaurants/show.html.haml
  spec/models/restaurant_note_spec.rb
Labels: test

#99 fixed #93 最新のグループ分けの詳細ページをHOME画面表示
  app/controllers/group_sets_controller.rb
  app/views/group_sets/show.html.haml
  config/routes.rb
Labels: enhancement

#83 fixed #70 フロントエンド改善
  app/assets/stylesheets/common.css
  app/assets/stylesheets/group_sets.css
  app/assets/stylesheets/matching_scores.css
  app/assets/stylesheets/restaurants.css
  app/views/group_sets/groups/edit.html.haml
  app/views/group_sets/groups/show.html.haml
  app/views/group_sets/index.html.haml
  app/views/group_sets/show.html.haml
  app/views/restaurants/edit.html.haml
  app/views/restaurants/index.html.haml
  app/views/restaurants/new.html.haml
  app/views/restaurants/show.html.haml
  app/views/users/index.html.haml
  app/views/users/matching_scores/index.html.haml
  config/routes.rb
Labels: enhancement

#101 fixed #100 お店ランダム選択機能の実装
  app/assets/stylesheets/group_sets.css
  app/controllers/group_sets/groups_controller.rb
  app/controllers/restaurant_notes_controller.rb
  app/controllers/restaurants_controller.rb
  app/models/restaurant.rb
  app/views/group_sets/groups/show.html.haml
Labels: enhancement

#92 fixed #89 口コミ編集機能の追加
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/common.css
  app/assets/stylesheets/restaurants.css
  app/controllers/restaurant_notes_controller.rb
  app/controllers/restaurants_controller.rb
  app/views/restaurant_notes/edit.html.haml
  app/views/restaurants/show.html.haml
  config/routes.rb
  frontend/src/javascripts/pages/restaurant_notes/restaurant_note_edit.js
  frontend/webpack.config.js
  spec/requests/restaurant_notes_controller_spec.rb
Labels: enhancement

#102 fixed #90 口コミ削除機能の実装
  app/assets/stylesheets/common.css
  app/controllers/restaurant_notes_controller.rb
  app/views/restaurants/show.html.haml
  config/routes.rb
  spec/requests/restaurant_notes_controller_spec.rb
Labels: enhancement

#111 fixed #110 お店のリンク改善
  app/assets/stylesheets/group_sets.css
  app/views/group_sets/groups/show.html.haml
  app/views/restaurants/show.html.haml
Labels: enhancement

#95 fixed #82 restaurant_notesコントローラーのテスト実装
  spec/requests/restaurant_notes_controller_spec.rb
Labels: test

#103 fixed #88 お店検索機能の実装（お店一覧ページ）
  app/assets/stylesheets/restaurants.css
  app/controllers/restaurants_controller.rb
  app/models/restaurant.rb
  app/views/restaurants/index.html.haml
Labels: enhancement

#104 fixed #87 お店検索機能（グループのお店追加時）
  app/assets/stylesheets/common.css
  app/assets/stylesheets/group_sets.css
  app/controllers/group_sets/groups_controller.rb
  app/controllers/restaurants_controller.rb
  app/views/group_sets/groups/edit.html.haml
  app/views/restaurants/index.html.haml
  app/views/restaurants/show.html.haml
Labels: enhancement
